name: Get CodeCov to work
env:
  codecov_token: "7a98a1aa-6020-4818-9400-5acf6fd37e8c"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip #bs4 pandas pyhelpers pygments sphinx
        python -m pip install -r requirements.txt
    - name: Run tests and collect coverage
      run: |
        python -m pip install pytest pytest-cov
        python -m pytest --cov  --cov-report xml:cov.xml .
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        files: cov.xml


